config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'
  resources :categories
  resources :votes, only: %i[create destroy]
  resources :articles do
    resources :votes
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
# frozen_string_literal: true

# class Article
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :tags, inverse_of: :article
  has_many :categories, through: :tags
  has_many :votes
  validates :title, :body, :image, :author_id, presence: true
  accepts_nested_attributes_for :tags

  scope :recent, -> { order(created_at: :desc).limit(1) }
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# class ArticlesController
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @popular_article = Vote.popular_article
    @categories = Category.priority_ordered
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @vote = if current_user.nil?
              nil
            else
              Vote.voteid(current_user.id, @article.id).take
            end
  end

  # GET /articles/new
  def new
    @article = Article.new
    @article.tags.build
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  # POST /articles.json

  def create
    @article = current_user.articles.build(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, :image, :author_id, tags_attributes: %i[category_id id])
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

# module ArticlesHelpler
module ArticlesHelper
  def main_properties(article)
    main_hash = if article.nil?
                  { image: 'defimg.jpg', title: '', link: '#' }
                else
                  { image: article.image,
                    title: article.title,
                    body: article.body }
                end
    main_hash
  end

  def article_properties(category)
    properties_hash = if category.articles.count.zero?
                        { image: 'defimg.jpg', title: '', link: '#' }
                      else
                        { image: category.articles.recent.first.image,
                          title: category.articles.recent.first.title,
                          link: category.articles.recent.first }
                      end
    properties_hash
  end

  def owner?(autor_id)
    current_user && autor_id == current_user.id
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.select :image, [['Log Cabin', 'logcabin'], ['Landscape', 'landscape'],
                             ['Pool', 'pool'], ['Minimalist', 'minimalist'],
                             ['Edible garden', 'ediblegarden'], ['Mountain','mountain']] %>
  </div>

  <div class="field">
    <%= form.fields_for :tags do |builder| %>
      <%= builder.label :category %>
      <%= builder.collection_select :category_id, Category.all, :id, :name %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="article-form-title">Editing Article</h1>

<%= render 'form', article: @article %>
<div class="lower-links">
  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="popular-article" style="background-image: linear-gradient(to top,
                    rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.2) 50%),
                    url(<%= image_path "#{main_properties(@popular_article)[:image]}"%>);">
  <h1 class="popular-title"><%= link_to main_properties(@popular_article)[:title], @popular_article%></h1>
  <p class="popular-body"><%= main_properties(@popular_article)[:body].truncate(200)%></p>
</div> 
<div class="category-container">
  <% @categories.each do |category| %>
    <article class='category-item' style="background-image: linear-gradient(to top,
                    rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0) 50%, rgba(0, 0, 0, 0.7) 100%),
                    url(<%= image_path "#{article_properties(category)[:image]}"%>);">
      <span class="lower-link category-link">
        <%= link_to category.name, category %>
      </span>
      <span class="lower-link article-link">
        <%= link_to article_properties(category)[:title], article_properties(category)[:link] %>
      </span>
    </article>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="article-form-title">New Article</h1>

<%= render 'form', article: @article %>

<div class="lower-links">
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<main class="article-container">
  <div class="text-content">
    <h1 class="article-title" >
      <%= @article.title %>
    </h1>
    <span class="article-info">
      <%= @article.author.name %> - <%= @article.created_at.strftime("%B %-d, %Y")%>
    </span>
    <article class= "body-content">
      <%= @article.body %>
    </article>
    <% if owner?(@article.author_id)%>
      <%= link_to 'Edit', edit_article_path(@article) %> |
    <% end %>
    <% if @vote.nil? %>
      <%= link_to 'Vote this article', article_votes_path( @article ), method: :post %>
    <% else %>
      <%= link_to 'Delete your vote', article_vote_path( id: @vote.id, article_id: @article.id  ), method: :delete %>
    <% end %>
  </div>
  <div class="image-content">
    <img class="article-image" src="<%= image_path @article.image %>" alt="article image" >
  </div>
</main>
<footer class="footer-container">
  <%= render :partial => 'categories/footer' %>
</footer>