config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'
  resources :categories
  resources :votes, only: %i[create destroy]
  resources :articles do
    resources :votes
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MountainBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>

  <body>
    <nav class="nav">
    <div class="home">
      <%= link_to root_path do%>
        <div class = "logo-text" >MounTAinsTyle</div>
      <% end %>
      <%= link_to root_path do%>
        <%= image_tag "mountains.png", alt: "Mountain Style Logo" %>
      <% end %>
    </div>
    <div class="menu">
      <% if user_signed_in? %>
          <%= link_to current_user.name, edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to 'New article', new_article_path, :class => 'navbar-link' %>
        </div>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <div class="menu-item">
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        </div>
        <div class="menu-item">
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        </div>
      <% end %>
    </div>
  </nav>
  	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
	  <% end %>
	  <% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
	  <% end %>
    <%= yield %>
  </body>
</html>